insert into Auditorium (movie, scrdate, seats) values ('Lion King', 12, 30);
insert into Auditorium (movie, scrdate, seats) values ('Lion King 2', 13, 20);
insert into Movie (title, description, subtitle, runtime) values ('Lion King', 'It is a very good movie', false, 110);
insert into Movie (title, description, subtitle, runtime) values ('Lion King 2', 'It is even a better movie', true, 123);
insert into Movie (title, description, subtitle, runtime) values ('Unknown Movie', 'This movie is not being aired', false, 0);
insert into Screening (auditoriumid, movieid, timeofscreening) values (1, 1, 1230);
insert into Screening (auditoriumid, movieid, timeofscreening) values (2, 1, 1500);
insert into Screening (auditoriumid, movieid, timeofscreening) values (3, 2, 1230);
insert into Visitor (reservationid, firstname, lastname, email, phone) values (NULL, 'First', 'Visitor', 'first.visitor@gmail.com', 201111111);

insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);
insert into Northauditoriumseats (reservationid) values (NULL);


insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);
insert into Southauditoriumseats (reservationid) values (NULL);